### ISSUE TITLE
Desktop Wallet for Mac

### ISSUE THREAD

**Issue by Boeremoon** [AidosKuneen/aidos-wallet#1]
The wallet for Mac doesn't work.

After registering with a seed, and then copy/pasting that seed into the seed/password field it gives me a CONNECTION REFUSED error.

Please can someone help.

**Comment by shagbag** [comment]
I get the same error on 64 bit Ubuntu 16.10

**Comment by Donrico77** [comment]
In the wallet Choose  : 
tools ->Edit Node Configuaration -> enter server adress:  wallet1.aidoskuneen.com

**Comment by Boeremoon** [comment]
Thanks. that worked.
