### ISSUE TITLE
PC wallet 2.0(window version) deposit address creation error

### ISSUE THREAD

**Issue by jms-h** [AidosKuneen/aidos-wallet#13]
My window version is win7
In the process of generating the deposit address, the wallet screen turns into an empty screen.
Check please !!!

**Comment by nochiu** [comment]
me too.


window 10 Pro x64 1903
OS build 18362.1139

**Comment by jedidavid** [comment]
Issue was fixed at [v2.0.1](https://github.com/AidosKuneen/aidos-wallet/releases/tag/2.0.1)
